### ISSUE TITLE
Enable public wiki

### ISSUE THREAD

**Issue by giuseppemorelli** [magespecialist/mage-chrome-toolbar#1]
Hi guys,
can you enable public wiki? (or I am unable to see?)
It shoul be beautiful to have 2 pages with Magento 1 features and Magento 2 features.
For example: profiler is only for magento

I can help you to write it. :)

Thank you!

**Comment by phoenix128** [comment]
Hi @giuseppemorelli ,
we just did it.

I do not understand what you mean by _profiler is only for magento_, do you mean that is only for Magento 1? We addedd Magento 1 support a coupole of releases ago.

**Comment by giuseppemorelli** [comment]
@phoenix128 sorry about that. I forgot the number 2 :)

I mean profiler is only for magento 2 (has your README).

Happy to listen that now is available for magento 1!

**Comment by phoenix128** [comment]
@giuseppemorelli , no problem, we probably forget to update the README. Where did you find it?

**Comment by giuseppemorelli** [comment]
REPOSITORY https://github.com/magespecialist/mage-chrome-toolbar

file README row 33 -> instruction only for magento 2

REPOSITORY https://github.com/magespecialist/m1-MSP_DevTools

No info about profiler (or not found)


How to enable profiler or magento 1?

Thanks :)

**Comment by phoenix128** [comment]
You do not need extra instruction for Magento 1, just turn it on as ususal with:

`Varien_Profiler::enable();`

In your `index.php` file.

**Comment by giuseppemorelli** [comment]
Ok!
Idea for the next release: just introduce xml config file like https://github.com/AOEpeople/Aoe_Profiler to enable profiling (and introduce more methods to enable it).
I'll try to send a Pull Request for that (if you want).

Ps. Hope the wiki pages created are good with your company guidelines

**Comment by phoenix128** [comment]
It should be quite easy to do, we can work on it.

**Comment by giuseppemorelli** [comment]
Great!
"Free time" to coding what I want is not my friend.
