### ISSUE TITLE
Installation does not work

### ISSUE THREAD

**Issue by DavidLambauer** [magespecialist/mage-chrome-toolbar#10]
Hi there,

I just tried to install the extension and the Chrome Browser Extension. I followed the README but nothing happens. The Browser Extension doesn't seem to work. 

Are there any debug information, that I can provide you? 

Greetings David

**Comment by phoenix128** [comment]
Did you install Magento module too?

**Comment by DavidLambauer** [comment]
Wow, that was a fast reply! 👍  

Yes I installed the Magento 2 Module.

**Comment by phoenix128** [comment]
Can you pls post your Magento 2 module's configuration?

**Comment by DavidLambauer** [comment]
Thank you for your help via Slack! 

The Extension now works, I just had to delete the local storage via chrome-dev-tools.

Love that extension! Thank you!
