### ISSUE TITLE
Profiler, Plugins and Queries tabs are always empty

### ISSUE THREAD

**Issue by Koc** [magespecialist/mage-chrome-toolbar#14]
![default](https://user-images.githubusercontent.com/191082/27516855-6116fe2c-59ca-11e7-83b4-835a8476b3c6.png)

**Comment by phoenix128** [comment]
Did you follow "Enabling profiler feature on Magento 2" guide? https://github.com/magespecialist/mage-chrome-toolbar#enabling-profiler-feature-on-magento-2

For queries it should display a warning message showing instructions. We will check why it is not doing that.

To fix it: 
You should set a new key for $config array in file app/etc/env.php:
$config[db][connection][default][profiler] = 1

**Comment by Koc** [comment]
Yes, it done. As you see from screenshot queries collects in another plugin. What do you think - can it be conflict with https://github.com/vpietri/magento2-developer-quickdevbar ?

**Comment by phoenix128** [comment]
Don't think so but you can try disabling the other to se if it fixes.
Otherwise we should go deeper.

**Comment by phoenix128** [comment]
Did it work?
