### ISSUE TITLE
Error installing Chrome Extension

### ISSUE THREAD

**Issue by davidverholen** [magespecialist/mage-chrome-toolbar#19]
I'm getting an Error when I try to add the extension to Chrome:
Package is invalid. Details: 'Could not load icon 'images/icon_off.png' for browser action.'.

(Immediately after Downloading)

I'm running Chrome Version 59.0.3071.115 on Ubuntu 17.04.

**Comment by phoenix128** [comment]
Hi @davidverholen ,
are you installing it from Chrome Extension Store?

**Comment by phoenix128** [comment]
Uhm... seems you are right. I do not know why, but it seems the previous update package was broken. That's weird.

We just uploaded it again with a version bump (3.3). It should be available in about 60 minutes. Can you please try again?

**Comment by phoenix128** [comment]
Just checked, now it is working.
Thank you for your report.

**Comment by davidverholen** [comment]
really awesome integration! working now as expected. I'm having an issue or maybe only a question, will open a new issue

**Comment by phoenix128** [comment]
Thank you for your appreciating our job :+1:
