### ISSUE TITLE
Inspector view error on Linux Mint Cinnamon 17.3 and Chrome 51

### ISSUE THREAD

**Issue by giuseppemorelli** [magespecialist/mage-chrome-toolbar#2]
Hi guys,
on my environment I have a little view error on inspector section (see screenshoot below).
Anything else has this error?

Thank you!

**Tech info**
OS: Linux mint 17.3
GUI: Cinnamon
Chrome Version: Version 51.0.2704.103 (64-bit)

![inspector-m1](https://cloud.githubusercontent.com/assets/1280769/18431101/c6af408a-78db-11e6-9c65-cbfd3326f1f1.png)

**Comment by phoenix128** [comment]
It is a known bug, upgrade Chrome.

**Comment by giuseppemorelli** [comment]
Wrote on FAQ section -> done :)
