### ISSUE TITLE
Widget Template File 

### ISSUE THREAD

**Issue by davidverholen** [magespecialist/mage-chrome-toolbar#20]
When I'm trying to open a custom widget file over the chrome dev tools, it always points me to the class:
/vendor/magento/module-cms/Block/Widget/Block.php
and the template:
/vendor/magento/module-cms/view/frontend/templates/widget/static_block/default.phtml

while it should be a custom widget class and template file. It's basically an extension of the product_link widget.

Not sure if this is just beyond limits of this integration?

**Comment by phoenix128** [comment]
Good point, not sure we tested with this scenario.

It is probably because Widget/Block.php class is encapsulating the Widget itself, but I think we can do something for it, it should not be too hard.

I'm putting this on the schedule of the next week. I'll keep you informed about that.

**Comment by davidverholen** [comment]
that would be really great.

just thinking, as we have projects with really many widgets and/or cms blocks.
Would it be possible, to display the widget name and block identifier for example?
sometimes it's getting really hard to find the right cms blocks for example when they are not following our naming convention

**Comment by phoenix128** [comment]
Yes sure. For CMS block it should be already working if I am not wrong, but probably with its ID, putting the identificator is a better idea. We will work on this.

**Comment by davidverholen** [comment]
ah right, I see the cms block id is working. This is really helpful! Gonna get all our devs on that ;)

**Comment by davidverholen** [comment]
I'm just seeing. Basically the dev toolbar wokrs as intended. We inserted a cms block and added the widgets inside of the block. So the module points to this cms block and the static block template.

**Comment by phoenix128** [comment]
We just released Chrome DevTools module 3.3.1 and m2-MSP_DevTools module 1.2.3 .
We singificantly increased blocks inspection details (including widgets).

Hope it helps ;)
