### ISSUE TITLE
Blocks in list don't link to the markup

### ISSUE THREAD

**Issue by lorenaramonda** [magespecialist/mage-chrome-toolbar#21]
Hi guys,
can't see the eye icon linking the markup of the block in the listing in M1
![schermata del 2017-08-01 11-14-13](https://user-images.githubusercontent.com/4409084/28818471-8a077480-76ab-11e7-96c5-57c3d80f3b47.png)

;)

**Comment by phoenix128** [comment]
Fixed in 1.2.1. https://github.com/magespecialist/m1-MSP_DevTools

Thank you ;)
