### ISSUE TITLE
Get block information from inspecting HTML

### ISSUE THREAD

**Issue by daaru00** [magespecialist/mage-chrome-toolbar#22]
There is a possibility to add a feature to select tag related block from HTML inspector? 
If not, is possible to add more information inside HTML comment after/before the block?
From:
```html
<!-- START_MSPDEV[xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx]: cms_page -->
<p>My block content</p>
<!-- /END_MSPDEV[xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx]: cms_page -->
```
To:
```html
<!-- START_MSPDEV[xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx]: cms_page template:/path/to/template.phtml -->
<p>My block content</p>
<!-- /END_MSPDEV[xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx]: cms_page -->
```

**Comment by phoenix128** [comment]
Hello @daaru00 ,
you have a full chrome inspector integration to do it.

Just open Chrome inspector as you do to debug a simple CSS and switch to "Magento" tab.

You basically have 2 Magento tabs in devtools extension:

- Global: the one showing global page inforamtion such as design informations, templates and so on.
- Inspector: it is a tab inside the inspector window showin information about the selected item in your DOM.

![devtools](https://user-images.githubusercontent.com/10189093/28826587-e860b54a-76ca-11e7-9045-75dd040be855.png)

**Comment by daaru00** [comment]
Oh sorry, I had the tabs collapsed next to the style and I did not see it!
That's exactly what I was looking for.

Thank you so much.
