### ISSUE TITLE
Using with vagrant box

### ISSUE THREAD

**Issue by tgamanov** [magespecialist/mage-chrome-toolbar#23]
Hi,

Works with the local installation, but if Magento running on virtual machine extension does not work.
Just showing standard error:
MSP DevTools information not available.
Please check:

This is a Magento website
You correctly installed MSP_DevTools
You enabled MSP_DevTools
You are within the allowed address range
Full installation and configuration guide:

https://github.com/magespecialist/mage-chrome-toolbar
How to install the Magento module:

This extension needs MSP_DevTools to be installed and configured in your Magento website.
Magento 1:

Download and copy in your Magento root path the MSP_DevTools module.
Source code is available on GitHub: https://github.com/magespecialist/m1-MSP_DevTools
Magento 2:

You can install using composer: composer require msp/devtools
Source code is available on GitHub: https://github.com/magespecialist/m2-MSP_DevTools

At admin settings instead of localhost, I have put IP of the vagrant box.

Please let me know if you need more details.
Thanks.

**Comment by tgamanov** [comment]
![settings at admin](https://user-images.githubusercontent.com/11708989/28936606-d9740722-7890-11e7-9a3f-b1f51d0e5969.png)
![module installed](https://user-images.githubusercontent.com/11708989/28936642-fe1672d6-7890-11e7-80f5-29a2f5c88fce.png)

**Comment by giacmir** [comment]
Hi @tgamanov we at Magespecialist use this extension on vagrant every day without problems. 
Try to put 0.0.0.0/0 as ip range (since you are on vagrant you don't need to filter ips).

Also make sure your full_page cache is turned off.

**Comment by tgamanov** [comment]
HI,

The hint with "0.0.0.0/0" helped.
Works.

Thank you for the quick response)

**Comment by hgati** [comment]
Hi, me too.

It is resolved by 0.0.0.0/0 setting.

Thanks all.
