### ISSUE TITLE
Please upgrade you Magento MSP_DevTools plugin.

### ISSUE THREAD

**Issue by mkor** [magespecialist/mage-chrome-toolbar#24]
This is the notice I get after Installing the extension in Chrome, the plugin in magento 2.1.7 and then enable it.

I followed the guide and only just installed both a couple of hours ago.

**Comment by phoenix128** [comment]
Can you please check what is the module version in your composer.lock file?

**Comment by mkor** [comment]
> "require": {
>         "magento/product-community-edition": "2.1.7",
>         "composer/composer": "@alpha",
>         "mollie/magento2": "^1.0",
>         "webshopapps/module-matrixrate": "^20.1",
>         "honl/magento2-nl-nl": "^1.1",
>         "msp/devtools": "^0.2.4"

**Comment by phoenix128** [comment]
You have an outdated locked version.

Try with:
`composer require msp/dev-tools:1.2.5`

Also remember to run:
`bin/magento setup:upgrade`

**Comment by mkor** [comment]
Thanks! That worked! :)

This DirectAdmin host has an issue with installed php versions. the default must remain 5.6 for certain reasons, while a number of websites of ours now runs 7.0.* But, the commandline similarly still defaults to 5.6, which seems to have led to the wrong version being installed.

**Comment by mattgreenfield** [comment]
I also had this issue when following the installation docs. Can something be added to up the default version to the latest in composer? Or would you be happy to see the docs updated with note of this fix?

Thanks

**Comment by phoenix128** [comment]
Hello @mattgreenfield ,
do you mean something like `composer require msp/devtools:dev-master`?

**Comment by mattgreenfield** [comment]
Well it just seems that `composer require msp/devtools` is getting version ^0.2.4 by default. Is there a way that default can be updated? Something to do with where the composer package is hosted (sorry I don't know much about composer).

But yes, the other 'fix' would be to update the docs to `composer require msp/devtools:dev-master` as you say.

Thanks

**Comment by phoenix128** [comment]
`composer require msp/devtools` downloads the version we marked as "last" in packagist.org (see https://packagist.org/packages/msp/devtools). At this very moment is **1.2.6**, so if you install msp/devtools for the first time now, you will get **1.2.6** version.

This version is stored in `composer.lock` file to guarantee backward compatibility with any custom module you could write integrating devtools (quite unusual, but it may happen).

So, if you just try to update it, you will get at **1.2.x** version even if an hypotetical **1.3.x** was released. If any minor/major version is released, you have to manually update it by asking composer for an explicit version or `dev-master` to mean the very latest.

Hope this can help you.
