### ISSUE TITLE
"Cannot set property stop of undefined" error in console

### ISSUE THREAD

**Issue by LucaGallinari** [magespecialist/mage-chrome-toolbar#3]
Hi, i have the latest version of the magento 1 module and this happen ONLY when i visit the homepage of my project. This does not happen in the admin control panel.

![schermata del 2016-09-23 11-32-16](https://cloud.githubusercontent.com/assets/5822554/18781311/71572892-8181-11e6-9b0c-e4cbab3a8013.png)

**Comment by LucaGallinari** [comment]
Ok, this is pretty awkward. I found out that the problem is related with the content of the CMS "block" of the homepage. 
- If i write something in it by using the WYSIWYG editor and then save, the extension will work. If i save again by not changing anything, it won't work. 
- If i write something and save, then re-edit the content by removing the auto-added "<p>" tag and save, it will work!
- If i disable the WYSIWYG editor in the system config, the extension will always work.
If there is a single "<p>" tag in the WYSIWYG the extension will generate that error.

**Comment by phoenix128** [comment]
We just released v.1.8 that should fix it. If you have Chrome for windows it will automatically upgrade in the very next minutes.
