### ISSUE TITLE
Magento 2.2.2 - Not Working

### ISSUE THREAD

**Issue by kauansoft** [magespecialist/mage-chrome-toolbar#30]
Magento 2.2.2
PHP 7.1
Report log:

{"0":"Invalid operation nesting","1":"#0 \/home\/site\/public_html\/vendor\/msp\/devtools\/Plugin\/View\/LayoutPlugin.php(115): MSP\\DevTools\\Model\\AbstractOpsRegistry->stop('root', Array)\n#1 \/home\/site\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(135): MSP\\DevTools\\Plugin\\View\\LayoutPlugin->aroundRenderElement(Object(Magento\\Framework\\View\\Layout\\Interceptor), Object(Closure), 'root')\n#2 \/home\/site\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Framework\\View\\Layout\\Interceptor->Magento\\Framework\\Interception\\{closure}('root')\n#3 \/home\/site\/public_html\/generated\/code\/Magento\/Framework\/View\/Layout\/Interceptor.php(195): Magento\\Framework\\View\\Layout\\Interceptor->___callPlugins('renderElement', Array, NULL)\n#4 \/home\/site\/public_html\/vendor\/magento\/framework\/View\/Layout.php(954): Magento\\Framework\\View\\Layout\\Interceptor->renderElement('root')\n#5 \/home\/site\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Framework\\View\\Layout->getOutput()\n#6 \/home\/site\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Framework\\View\\Layout\\Interceptor->___callParent('getOutput', Array)\n#7 \/home\/site\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Framework\\View\\Layout\\Interceptor->Magento\\Framework\\Interception\\{closure}()\n#8 \/home\/site\/public_html\/generated\/code\/Magento\/Framework\/View\/Layout\/Interceptor.php(494): Magento\\Framework\\View\\Layout\\Interceptor->___callPlugins('getOutput', Array, Array)\n#9 \/home\/site\/public_html\/vendor\/magento\/framework\/View\/Result\/Page.php(257): Magento\\Framework\\View\\Layout\\Interceptor->getOutput()\n#10 \/home\/site\/public_html\/vendor\/magento\/framework\/View\/Result\/Layout.php(170): Magento\\Framework\\View\\Result\\Page->render(Object(Magento\\Framework\\App\\Response\\Http\\Interceptor))\n#11 \/home\/site\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Framework\\View\\Result\\Layout->renderResult(Object(Magento\\Framework\\App\\Response\\Http\\Interceptor))\n#12 \/home\/site\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Framework\\View\\Result\\Page\\Interceptor->___callParent('renderResult', Array)\n#13 \/home\/site\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Framework\\View\\Result\\Page\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Response\\Http\\Interceptor))\n#14 \/home\/site\/public_html\/generated\/code\/Magento\/Framework\/View\/Result\/Page\/Interceptor.php(130): Magento\\Framework\\View\\Result\\Page\\Interceptor->___callPlugins('renderResult', Array, Array)\n#15 \/home\/site\/public_html\/vendor\/magento\/framework\/App\/Http.php(139): Magento\\Framework\\View\\Result\\Page\\Interceptor->renderResult(Object(Magento\\Framework\\App\\Response\\Http\\Interceptor))\n#16 \/home\/site\/public_html\/generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php(24): Magento\\Framework\\App\\Http->launch()\n#17 \/home\/site\/public_html\/vendor\/magento\/framework\/App\/Bootstrap.php(256): Magento\\Framework\\App\\Http\\Interceptor->launch()\n#18 \/home\/site\/public_html\/index.php(39): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#19 {main}","url":"\/","script_name":"\/index.php"}

**Comment by phoenix128** [comment]
Hello @kauansoft ,
did you see if you have the same issue with default template?

**Comment by gjportegies** [comment]
Magento 2.2.3
PHP 7.0.29
Report log:

{"0":"Class Magento\\Framework\\Controller\\Result\\ForwardFactory does not exist in [Magento\\Cms\\Controller\\Index\\Index\\Interceptor]","1":"#0 \/home\/domains\/example.com\/web\/vendor\/magento\/framework\/Code\/Generator\/Autoloader.php(35): Magento\\Framework\\Code\\Generator->generateClass('Magento\\\\Cms\\\\Con...')\n#1 [internal function]: Magento\\Framework\\Code\\Generator\\Autoloader->load('Magento\\\\Cms\\\\Con...')\n#2 [internal function]: spl_autoload_call('Magento\\\\Cms\\\\Con...')\n#3 \/home\/domains\/example.com\/web\/vendor\/magento\/framework\/Code\/Reader\/ClassReader.php(19): ReflectionClass->__construct('Magento\\\\Cms\\\\Con...')\n#4 \/home\/domains\/example.com\/web\/vendor\/magento\/framework\/ObjectManager\/Definition\/Runtime.php(44): Magento\\Framework\\Code\\Reader\\ClassReader->getConstructor('Magento\\\\Cms\\\\Con...')\n#5 \/home\/domains\/example.com\/web\/vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php(48): Magento\\Framework\\ObjectManager\\Definition\\Runtime->getParameters('Magento\\\\Cms\\\\Con...')\n#6 \/home\/domains\/example.com\/web\/vendor\/magento\/framework\/ObjectManager\/ObjectManager.php(56): Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->create('Magento\\\\Cms\\\\Con...', Array)\n#7 \/home\/domains\/example.com\/web\/vendor\/magento\/framework\/App\/ActionFactory.php(40): Magento\\Framework\\ObjectManager\\ObjectManager->create('Magento\\\\Cms\\\\Con...')\n#8 \/home\/domains\/example.com\/web\/vendor\/magento\/framework\/App\/Router\/Base.php(297): Magento\\Framework\\App\\ActionFactory->create('Magento\\\\Cms\\\\Con...')\n#9 \/home\/domains\/example.com\/web\/vendor\/magento\/framework\/App\/Router\/Base.php(158): Magento\\Framework\\App\\Router\\Base->matchAction(Object(Magento\\Framework\\App\\Request\\Http), Array)\n#10 \/home\/domains\/example.com\/web\/vendor\/magento\/framework\/App\/FrontController.php(50): Magento\\Framework\\App\\Router\\Base->match(Object(Magento\\Framework\\App\\Request\\Http))\n#11 \/home\/domains\/example.com\/web\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Framework\\App\\FrontController->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#12 \/home\/domains\/example.com\/web\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Framework\\App\\FrontController\\Interceptor->___callParent('dispatch', Array)\n#13 \/home\/domains\/example.com\/web\/vendor\/magento\/module-store\/App\/FrontController\/Plugin\/RequestPreprocessor.php(94): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#14 \/home\/domains\/example.com\/web\/vendor\/magento\/framework\/Interception\/Interceptor.php(135): Magento\\Store\\App\\FrontController\\Plugin\\RequestPreprocessor->aroundDispatch(Object(Magento\\Framework\\App\\FrontController\\Interceptor), Object(Closure), Object(Magento\\Framework\\App\\Request\\Http))\n#15 \/home\/domains\/example.com\/web\/app\/code\/TemplateMonster\/LayoutSwitcher\/Model\/App\/Action\/ContextPlugin.php(40): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#16 \/home\/domains\/example.com\/web\/vendor\/magento\/framework\/Interception\/Interceptor.php(135): TemplateMonster\\LayoutSwitcher\\Model\\App\\Action\\ContextPlugin->aroundDispatch(Object(Magento\\Framework\\App\\FrontController\\Interceptor), Object(Closure), Object(Magento\\Framework\\App\\Request\\Http))\n#17 \/home\/domains\/example.com\/web\/vendor\/magento\/module-page-cache\/Model\/App\/FrontController\/BuiltinPlugin.php(69): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#18 \/home\/domains\/example.com\/web\/app\/code\/TemplateMonster\/SiteMaintenance\/Model\/PageCache\/App\/FrontController\/BuiltinPlugin.php(30): Magento\\PageCache\\Model\\App\\FrontController\\BuiltinPlugin->aroundDispatch(Object(Magento\\Framework\\App\\FrontController\\Interceptor), Object(Closure), Object(Magento\\Framework\\App\\Request\\Http))\n#19 \/home\/domains\/example.com\/web\/vendor\/magento\/framework\/Interception\/Interceptor.php(135): TemplateMonster\\SiteMaintenance\\Model\\PageCache\\App\\FrontController\\BuiltinPlugin->aroundDispatch(Object(Magento\\Framework\\App\\FrontController\\Interceptor), Object(Closure), Object(Magento\\Framework\\App\\Request\\Http))\n#20 \/home\/domains\/example.com\/web\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#21 \/home\/domains\/example.com\/web\/generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php(26): Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins('dispatch', Array, NULL)\n#22 \/home\/domains\/example.com\/web\/vendor\/magento\/framework\/App\/Http.php(135): Magento\\Framework\\App\\FrontController\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#23 \/home\/domains\/example.com\/web\/generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php(24): Magento\\Framework\\App\\Http->launch()\n#24 \/home\/domains\/example.com\/web\/vendor\/magento\/framework\/App\/Bootstrap.php(256): Magento\\Framework\\App\\Http\\Interceptor->launch()\n#25 \/home\/domains\/example.com\/web\/index.php(39): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#26 {main}","url":"\/","script_name":"\/index.php"}

**Comment by chireenjavier** [comment]
What was the solution for this?

**Comment by lucasvm** [comment]
You need to add this at the top of your controller, under namespace

use Magento\Backend\Model\View\Result\ForwardFactory;
