### ISSUE TITLE
Profiler - No results and icon does not look colorful

### ISSUE THREAD

**Issue by guilhermetb** [magespecialist/mage-chrome-toolbar#33]
I followed the content https://github.com/magespecialist/mage-chrome-toolbar

**"Add the following line at the very beginning on index.php and pub/index.php"**
![image](https://user-images.githubusercontent.com/29417098/48532830-22fd7680-e889-11e8-9a6f-b6a65bf91fd9.png)
![image](https://user-images.githubusercontent.com/29417098/48532844-2f81cf00-e889-11e8-89ac-d4b5926866b6.png)

**"Editing .htaccess file"**
![image](https://user-images.githubusercontent.com/29417098/48532872-4fb18e00-e889-11e8-94f5-4cae68699527.png)

**All other functions are correct, I'm having problems only with the profiler tab**
![image](https://user-images.githubusercontent.com/29417098/48533088-36f5a800-e88a-11e8-8838-945eaffb844d.png)

**Comment by anatolij-p** [comment]
Same issue here.

**Comment by MurKit** [comment]
Same issue here. Idk, looks like the problem is in the Magento installation itself, because 
`SetEnv MAGE_PROFILER html`
doesn't work too.

**Comment by mzeis** [comment]
I'm arriving late to the party, but if anyone is still looking for this: in modern versions, you use `bin/magento` instead to the above settings to configure the profiler:

~~~
bin/magento dev:profiler:enable 'MSP\DevTools\Profiler\Driver\Standard\Output\DevTools'
~~~

**Comment by onlinemusketeers** [comment]
@mzeis awesome. thanks for this ! now it works.  They should add this to the install. instructions @magespecialist

**Comment by slackerzz** [comment]
Would you like to submit a pull request to update the Readme?
