### ISSUE TITLE
Unsafe Chrome Web Store App / down from Store

### ISSUE THREAD

**Issue by Morgy93** [magespecialist/mage-chrome-toolbar#39]
<img width="695" alt="image" src="https://user-images.githubusercontent.com/7961978/175884579-0f58da34-5b44-4f7d-ad75-4e9f22d6d20e.png">
Translates to: This extension has been disabled because it was deemed unsafe by the Chrome Web Store.

The store link returns 404: 
- Readme: https://chrome.google.com/webstore/detail/magespecialist-devtools-f/odbnbnenehdodpnebgldhhmicbnlmapj?authuser=3
- Browser: https://chrome.google.com/webstore/detail/odbnbnenehdodpnebgldhhmicbnlmapj

What's wrong here?

**Comment by ignaciomella** [comment]
I'm having the same issue.

**Comment by slackerzz** [comment]
We are looking into this issue, in the meantime you can download this repo and then install the extension following this guide https://developer.chrome.com/docs/extensions/mv3/getstarted/#unpacked

Or use the crx file attached [mage-chrome-toolbar-master.crx.zip](https://github.com/magespecialist/mage-chrome-toolbar/files/9081454/mage-chrome-toolbar-master.crx.zip)

**Comment by instalab** [comment]
@slackerzz That does not work, chrome throws an error "CRX_HEADER_INVALID".
I think this extension needs updating.

**Comment by slackerzz** [comment]
@instalab i've just loaded the extension in a clean chrome profile following the guide for unpacked extensions linked in my previous comment ant it works

**Comment by Eddcapone** [comment]
Why is chrome saying it is unsafe though?

**Comment by slackerzz** [comment]
@Eddcapone because the extension was asking for two permissions (tabs and webNavigation) and not using them

**Comment by slackerzz** [comment]
the extension is available again https://chrome.google.com/webstore/detail/magespecialist-devtools-f/odbnbnenehdodpnebgldhhmicbnlmapj
