### ISSUE TITLE
Full Page Cache seems enabled

### ISSUE THREAD

**Issue by gamerboy** [magespecialist/mage-chrome-toolbar#4]
Hi,
in my Chrome DevTools i always get a "Full Page Cache seems enabled" warning, even if FPC was disabled.  
Any suggestion?

Best regards,
Andrea.

![2016-11-22](https://cloud.githubusercontent.com/assets/4609259/20529022/d1bb45c0-b0ce-11e6-82e3-dab3869efe66.png)

**Comment by giacmir** [comment]
Please see https://github.com/magespecialist/m2-MSP_DevTools/issues/2
does it solve for you?

**Comment by gamerboy** [comment]
How fast!

Yes, it was my fault.
I forgot that my web server is running on a private VirtualBox network with a different IP class.

Thank you.
Closed!
