### ISSUE TITLE
Chrome extension url is not working.

### ISSUE THREAD

**Issue by milanu13** [magespecialist/mage-chrome-toolbar#41]
The chrome extension downloading URL is not working. Am I missing something? Thank You. [Chrome WebStore](https://chrome.google.com/webstore/detail/magespecialist-devtools-f/odbnbnenehdodpnebgldhhmicbnlmapj?authuser=3)

**Comment by giacmir** [comment]
Yes, our extension has been marked as "unsafe" and removed from the store. We are working on it. In the meanwhile you can install it manually in "developer mode".

see #39
