### ISSUE TITLE
FPC seems enabled

### ISSUE THREAD

**Issue by dzmcclur** [magespecialist/mage-chrome-toolbar#5]
Getting the Full Page Cache seems enabled issue, I have all caches disabled. I read the other issues and they seemed to pertain to VMs, and this machine is not a VM but a server with it's own IP.

I'm sure that I have the correct IP set in the Authorized IP List field, on a site and store view level.

![image](https://cloud.githubusercontent.com/assets/12162415/20775142/7eebad4e-b727-11e6-9099-f83fe6537028.png)

**Comment by phoenix128** [comment]
Please open a Megento page and check if at the very end of HTML source code you can see the DevTools output. It is a long Javascript code you will recognize.

Just for a test: try setting 0.0.0.0/0 as IP in the authorized list even if you are sure about the IP.

**Comment by dzmcclur** [comment]
Setting the IP at 0.0.0.0 worked, and the javascript code for DevTools is now showing at the bottom (it was not before).

**Comment by phoenix128** [comment]
Fine... we will check for problems on the IP filter.
