### ISSUE TITLE
After installation no option found in side STORE>CONFIG as per instruction.

### ISSUE THREAD

**Issue by dkrvl** [magespecialist/mage-chrome-toolbar#6]
As per instruction for MAGENTO 2 I was installed it, but there is no option found in Magento Backed > STORE> CONFIG>.

  - Magento 2.1
 - Window 10
 - Installation using git's bash.exe Like below command
 `php composer.phar require msp/devtools`
 - msp/devtools(v -  ^0.1.6) installed
 - composer.json is updated.

**Comment by phoenix128** [comment]
Hello @dkrvl,
did you run `php bin/magento setup:upgrade` ?

**Comment by dkrvl** [comment]
not did before issue posted.

After posting i run the below command and the msp devtool menu now showing.

php bin/magento setup:upgrade 
php bin/magento setup:di:compile 
php bin/magento setup:static-content:deploy 
php bin/magento indexer:reindex 
php bin/magento cache:clean 
php bin/magento cache:flush

please include/update the instruction of steps on page.

Thanks for reply.

**Comment by phoenix128** [comment]
If you need such steps you are probably on a production environment.

You should switch to developer environment:

`php bin/magento deploy:mode:set developer`

**Comment by dkrvl** [comment]
i was already playing :) on developer mode. After doing as per you said setup:upgrade and other command(as above) runs. it was works.

And about steps update only update steps which needed.... may be i was over-write...commands.
